-- =============================================================================
-- 01_tables.sql - KingsArena schema extensions (teams, richer tournaments,
--                  participant-based fixtures).
--
-- Design rules for this file:
--   * Re-runnable. Every object uses IF NOT EXISTS / DROP-then-ADD so the file
--     can be applied against a live database repeatedly without losing data.
--   * The only intentional DELETE is of public.fixtures rows, because fixtures
--     are derived data and can always be regenerated by
--     public.generate_fixtures() (see 02_functions.sql).
--
-- NOTE ON RLS: this file does NOT touch policies. The broken policies that
-- compare auth.uid() to a profiles.id column are repaired in 04_rls_grants.sql.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 0. Extensions
-- -----------------------------------------------------------------------------
create extension if not exists "uuid-ossp";


-- =============================================================================
-- 1. TEAMS
-- =============================================================================

-- A team is a group of players that can enter a tournament as a single unit.
create table if not exists public.teams (
  id          uuid primary key default gen_random_uuid(),
  name        text not null unique
              check (char_length(btrim(name)) between 3 and 40),
  description text,
  game        text not null
              check (game in ('dls', 'efootball', 'fcmobile', 'cod')),
  owner_id    uuid not null references public.profiles(id) on delete cascade,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

comment on table public.teams is
  'Player teams. The owner is auto-added to team_members as role ''owner'' by a trigger in 02_functions.sql.';

-- Team roster. unique (team_id, user_id) prevents duplicate memberships.
create table if not exists public.team_members (
  id        uuid primary key default gen_random_uuid(),
  team_id   uuid not null references public.teams(id) on delete cascade,
  user_id   uuid not null references public.profiles(id) on delete cascade,
  role      text not null default 'member'
            check (role in ('owner', 'captain', 'member')),
  joined_at timestamptz not null default now(),
  unique (team_id, user_id)
);

comment on table public.team_members is
  'Team roster. Non-owner rows are inserted by the client; the owner row comes from a trigger.';


-- =============================================================================
-- 2. TOURNAMENTS - richer columns + integrity constraints
-- =============================================================================
create table if not exists public.tournaments (
  id uuid primary key default gen_random_uuid(),
  organizer_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  description text,
  game text not null,
  format text not null default 'league'
    check (format in ('league', 'knockout', 'group_knockout')),
  status text not null default 'upcoming'
    check (status in ('upcoming', 'registration', 'ongoing', 'completed', 'cancelled')),
  max_participants integer check (max_participants is null or max_participants > 1),
  start_date timestamptz,
  end_date timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Cover image for the tournament card.
alter table public.tournaments add column if not exists image_url text;

-- Free-form house rules shown to entrants.
alter table public.tournaments add column if not exists rules text;

-- Money columns. Defaults keep them non-null so client code never has to
-- coalesce; checks forbid negative amounts.
alter table public.tournaments add column if not exists entry_fee numeric(10, 2);
alter table public.tournaments add column if not exists prize_pool numeric(12, 2);
update public.tournaments set entry_fee = 0 where entry_fee is null;
update public.tournaments set prize_pool = 0 where prize_pool is null;
alter table public.tournaments alter column entry_fee set not null;
alter table public.tournaments alter column prize_pool set not null;

-- Last moment a participant may register. NULL means "no deadline".
alter table public.tournaments add column if not exists registration_deadline timestamptz;

-- Constraint names are explicit so the file can drop and re-add them safely.
alter table public.tournaments drop constraint if exists tournaments_entry_fee_check;
alter table public.tournaments add constraint tournaments_entry_fee_check
  check (entry_fee >= 0);

alter table public.tournaments drop constraint if exists tournaments_prize_pool_check;
alter table public.tournaments add constraint tournaments_prize_pool_check
  check (prize_pool >= 0);

-- The pre-existing table has no check on `game` at all.
-- Normalise any out-of-range game value to 'dls' BEFORE adding the constraint,
-- otherwise the ALTER fails on legacy rows. Coercion map:
--   any value not in ('dls','efootball','fcmobile','cod') -> 'dls'
do $$
declare
  v_offending integer;
begin
  select count(*)
    into v_offending
  from public.tournaments
  where game not in ('dls', 'efootball', 'fcmobile', 'cod');
  if v_offending > 0 then
    update public.tournaments
       set game = 'dls'
     where game not in ('dls', 'efootball', 'fcmobile', 'cod');
    raise notice 'Coerced % tournament(s) with unknown game value to ''dls''', v_offending;
  end if;
end
$$;

alter table public.tournaments drop constraint if exists tournaments_game_check;
alter table public.tournaments add constraint tournaments_game_check
  check (game in ('dls', 'efootball', 'fcmobile', 'cod'));

-- Normalise names that are too short BEFORE adding the check, otherwise the
-- ALTER fails on legacy rows. Coercion map:
--   names shorter than 3 chars after btrim -> padded with 'Tournament' suffix
--   so char_length(btrim(name)) lands between 3 and 100.
do $$
declare
  v_offending integer;
begin
  select count(*)
    into v_offending
  from public.tournaments
  where char_length(btrim(name)) not between 3 and 100;
  if v_offending > 0 then
    update public.tournaments
       set name = btrim(name) || 'Tournament'
     where char_length(btrim(name)) < 3;
    raise notice 'Padded % tournament name(s) that were shorter than 3 chars', v_offending;
  end if;
end
$$;

alter table public.tournaments drop constraint if exists tournaments_name_check;
alter table public.tournaments add constraint tournaments_name_check
  check (char_length(btrim(name)) between 3 and 100);


alter table public.tournaments drop constraint if exists tournaments_image_url_check;
alter table public.tournaments add constraint tournaments_image_url_check
  check (image_url is null or image_url ~ '^https?://');


-- =============================================================================
-- 3. TOURNAMENT PARTICIPANTS - a row is either an individual OR a team
-- =============================================================================
create table if not exists public.tournament_participants (
  id uuid primary key default gen_random_uuid(),
  tournament_id uuid not null references public.tournaments(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  unique (tournament_id, user_id)
);

-- Setting team_id makes this a team entry instead of a player entry.
alter table public.tournament_participants
  add column if not exists team_id uuid references public.teams(id) on delete cascade;

-- Exactly one side must be set: a player OR a team, never both or neither.
alter table public.tournament_participants
  drop constraint if exists tournament_participants_participant_check;
alter table public.tournament_participants add constraint tournament_participants_participant_check
  check ((user_id is not null and team_id is null)
      or (user_id is null  and team_id is not null));

-- Lifecycle state. 'eliminated' is what generate_next_round() aggregates over
-- to work out who is still alive in a bracket.
alter table public.tournament_participants
  add column if not exists status text not null default 'registered';

alter table public.tournament_participants
  drop constraint if exists tournament_participants_status_check;
alter table public.tournament_participants add constraint tournament_participants_status_check
  check (status in ('registered', 'withdrawn', 'eliminated'));

-- Optional manual seed, used to order bracket / round-robin pairings.
alter table public.tournament_participants add column if not exists seed integer;

-- Must become nullable now that team entries exist.
alter table public.tournament_participants alter column user_id drop not null;

-- The pre-existing unique (tournament_id, user_id) is intentionally KEPT and
-- still blocks duplicate individual registrations. Postgres treats NULLs as
-- distinct in unique constraints, so team rows (user_id IS NULL) never collide
-- with each other or with individual entries. If per-team uniqueness is ever
-- needed, add a separate unique (tournament_id, team_id).

-- =============================================================================
-- 4. FIXTURES - migrate from profile-based sides to PARTICIPANT-based sides
--
-- A side is now a tournament_participants row, which is itself either a player
-- or a team. That indirection is what lets a single bracket serve both.
-- =============================================================================
create table if not exists public.fixtures (
  id uuid primary key default gen_random_uuid(),
  tournament_id uuid not null references public.tournaments(id) on delete cascade,
  home_player_id uuid not null references public.profiles(id) on delete cascade,
  away_player_id uuid not null references public.profiles(id) on delete cascade,
  round integer,
  status text not null default 'scheduled'
    check (status in ('scheduled', 'ongoing', 'completed', 'cancelled')),
  scheduled_at timestamptz,
  created_at timestamptz not null default now(),
  check (home_player_id <> away_player_id)
);

-- Guarded purge. Fixtures are derived data, and home_player_id /
-- away_player_id are meaningless in the participant model. Wrapped in a block
-- so re-running the file is a cheap no-op when there is nothing to clear.
do $$
begin
  if exists (select 1 from public.fixtures) then
    delete from public.fixtures;
    raise notice 'Cleared existing fixtures rows for participant-based migration';
  end if;
end
$$;

-- The old NOT NULL columns MUST be dropped before the new check constraints are
-- added below, otherwise adding fixtures_home_away_check fails while rows still
-- carry NULL in the newly added participant columns.
-- Drop EVERY existing policy on public.fixtures first. The hand-built DB has
-- legacy policies that reference home_player_id / away_player_id, and Postgres
-- refuses the column drop while they exist. The correct policies are recreated
-- in 04_rls_grants.sql.
do $$
declare p record;
begin
  for p in select policyname from pg_policies where schemaname='public' and tablename='fixtures'
  loop
    execute format('drop policy if exists %I on public.fixtures', p.policyname);
  end loop;
end
$$;

alter table public.fixtures drop column if exists home_player_id;
alter table public.fixtures drop column if exists away_player_id;


alter table public.fixtures
  add column if not exists home_participant_id uuid
  references public.tournament_participants(id) on delete cascade;
alter table public.fixtures
  add column if not exists away_participant_id uuid
  references public.tournament_participants(id) on delete cascade;

-- Sequential ordering across the whole tournament, independent of round.
alter table public.fixtures add column if not exists match_number integer;

alter table public.fixtures add column if not exists updated_at timestamptz not null default now();

alter table public.fixtures drop constraint if exists fixtures_home_away_check;
alter table public.fixtures add constraint fixtures_home_away_check
  check (home_participant_id is not null
     and away_participant_id is not null
     and home_participant_id <> away_participant_id);

-- 'ongoing' is intentionally gone: a match is scheduled or finished.
-- sync_fixture_status() (02_functions.sql) flips it to 'completed' as soon as
-- both scores are present.
alter table public.fixtures drop constraint if exists fixtures_status_check;
alter table public.fixtures add constraint fixtures_status_check
  check (status in ('scheduled', 'completed', 'cancelled'));


-- =============================================================================
-- 5. FIXTURE RESULTS - NULL scores mean "not reported yet"
--
-- Semantics: no row at all == pending. A row with non-null scores and
-- status = 'submitted' == played, and the fixture is auto-marked completed by
-- the sync_fixture_status() trigger.
-- =============================================================================
create table if not exists public.fixture_results (
  fixture_id uuid primary key references public.fixtures(id) on delete cascade,
  home_score integer not null default 0 check (home_score >= 0),
  away_score integer not null default 0 check (away_score >= 0),
  submitted_by uuid not null references public.profiles(id) on delete cascade,
  submitted_at timestamptz not null default now()
);

-- Scores are nullable so a match can be opened before it is played, and
-- submitted_by is nullable so a result row can exist without a submitter
-- (system/admin confirmed results).
alter table public.fixture_results alter column home_score  drop not null;
alter table public.fixture_results alter column away_score  drop not null;
alter table public.fixture_results alter column submitted_by drop not null;

alter table public.fixture_results add column if not exists status text not null default 'pending';

alter table public.fixture_results drop constraint if exists fixture_results_status_check;
alter table public.fixture_results add constraint fixture_results_status_check
  check (status in ('pending', 'submitted'));

-- Optional match notes / highlights.
alter table public.fixture_results add column if not exists notes text;

alter table public.fixture_results add column if not exists updated_at timestamptz not null default now();

-- =============================================================================
-- 6. INDEXES
-- Covers the real query paths; none of these are implied by PK/UNIQUE
-- constraints. All IF NOT EXISTS so the file is re-runnable.
-- =============================================================================
create index if not exists tournament_participants_tournament_id_idx
  on public.tournament_participants (tournament_id);

create index if not exists tournament_participants_tournament_id_status_idx
  on public.tournament_participants (tournament_id, status);

create index if not exists tournament_participants_team_id_idx
  on public.tournament_participants (team_id);

create index if not exists team_members_user_id_idx
  on public.team_members (user_id);

create index if not exists teams_owner_id_idx
  on public.teams (owner_id);

create index if not exists fixtures_tournament_id_idx
  on public.fixtures (tournament_id);

create index if not exists fixtures_home_participant_id_idx
  on public.fixtures (home_participant_id);

create index if not exists fixtures_away_participant_id_idx
  on public.fixtures (away_participant_id);

create index if not exists fixture_results_submitted_by_idx
  on public.fixture_results (submitted_by);

-- Team entries are currently NOT deduplicated, because the
-- unique (tournament_id, user_id) constraint does not apply when user_id is
-- NULL (Postgres treats NULLs as distinct). This partial unique index closes
-- that gap: it prevents a team from registering twice for the same tournament.
create unique index if not exists tournament_participants_tournament_team_key
  on public.tournament_participants (tournament_id, team_id)
  where team_id is not null;
