-- =============================================================================
-- 04_rls_grants.sql -- Row Level Security policies and PostgREST grants
--
-- Depends on: 01_tables.sql, 02_functions.sql, 03_views.sql
-- Run order:  01 -> 02 -> 03 -> 04
--
-- THE BUG THIS FILE FIXES
-- ------------------------
-- public.profiles.id is a random uuid generated by the database; it is NOT
-- auth.users.id. Policies that compared auth.uid() against a profiles.id
-- column could never be true, so every insert/update/delete on tournaments and
-- tournament_participants was denied. From here on, ownership checks use
-- public.current_profile_id(), which resolves the signed-in user's profiles.id.
-- auth.uid() is still correct for public.profiles.user_id.
--
-- Every policy is dropped before being recreated, so this file is re-runnable
-- and stale/broken policies from earlier migrations cannot survive.
-- =============================================================================


-- =============================================================================
-- 1. ENABLE ROW LEVEL SECURITY  (idempotent)
-- =============================================================================

ALTER TABLE public.profiles                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tournaments             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tournament_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fixtures                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fixture_results         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teams                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members            ENABLE ROW LEVEL SECURITY;

-- =============================================================================
-- 1b. POLICY SWEEP (defensive)
-- The hand-built DB may carry legacy policies with unknown names that would
-- survive the named drops below and get OR-ed into the new policies, granting
-- unintended access. Sweeping ALL policies off these seven tables up front
-- makes the named drops redundant and guarantees a clean slate.
-- =============================================================================
do $$
declare
  t text;
  p record;
begin
  foreach t in array ARRAY[
    'profiles', 'tournaments', 'tournament_participants',
    'fixtures', 'fixture_results', 'teams', 'team_members'
  ] loop
    for p in
      select policyname from pg_policies
      where schemaname = 'public' and tablename = t
    loop
      execute format('drop policy if exists %I on public.%I', p.policyname, t);
    end loop;
  end loop;
end
$$;

-- =============================================================================
-- 2. POLICIES -- public.profiles
--
-- Profiles are world readable (public leaderboards need them).
-- There is deliberately no INSERT policy: the handle_new_user trigger creates
-- the row, so clients cannot forge profiles. No DELETE policy.
-- =============================================================================

DROP POLICY IF EXISTS "Profiles are viewable by everyone" ON public.profiles;
DROP POLICY IF EXISTS "Anyone can view profiles"          ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile"       ON public.profiles;

CREATE POLICY "Anyone can view profiles"
  ON public.profiles
  FOR SELECT
  USING (true);

-- Correct as written: profiles.user_id stores auth.users.id.
CREATE POLICY "Users can update own profile"
  ON public.profiles
  FOR UPDATE
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());


-- =============================================================================
-- 3. POLICIES -- public.tournaments
-- organizer_id references profiles.id, hence public.current_profile_id().
-- =============================================================================

DROP POLICY IF EXISTS "Anyone can view tournaments"   ON public.tournaments;
DROP POLICY IF EXISTS "Users can create tournaments"  ON public.tournaments;
DROP POLICY IF EXISTS "Organizers can update tournaments" ON public.tournaments;
DROP POLICY IF EXISTS "Organizers can delete tournaments" ON public.tournaments;

CREATE POLICY "Anyone can view tournaments"
  ON public.tournaments
  FOR SELECT
  USING (true);

CREATE POLICY "Users can create tournaments"
  ON public.tournaments
  FOR INSERT
  WITH CHECK (organizer_id = public.current_profile_id());

CREATE POLICY "Organizers can update tournaments"
  ON public.tournaments
  FOR UPDATE
  USING (organizer_id = public.current_profile_id())
  WITH CHECK (organizer_id = public.current_profile_id());

CREATE POLICY "Organizers can delete tournaments"
  ON public.tournaments
  FOR DELETE
  USING (organizer_id = public.current_profile_id());


-- =============================================================================
-- 4. POLICIES -- public.tournament_participants
--
-- Individuals register themselves; team entries are allowed when the caller is
-- a member of that team. public.can_join_tournament() is SECURITY DEFINER, so
-- it can check capacity, the registration window and registration status without
-- this policy recursing through RLS on tournaments.
-- =============================================================================

DROP POLICY IF EXISTS "Anyone can view tournament participants"     ON public.tournament_participants;
DROP POLICY IF EXISTS "Users can join tournaments"                 ON public.tournament_participants;
DROP POLICY IF EXISTS "Participants can update their registration" ON public.tournament_participants;
DROP POLICY IF EXISTS "Users can leave tournaments"                ON public.tournament_participants;

CREATE POLICY "Anyone can view tournament participants"
  ON public.tournament_participants
  FOR SELECT
  USING (true);

CREATE POLICY "Users can join tournaments"
  ON public.tournament_participants
  FOR INSERT
  WITH CHECK (
    (user_id = public.current_profile_id()
     OR (team_id IS NOT NULL AND public.is_team_member(team_id)))
    AND public.can_join_tournament(tournament_id)
  );

CREATE POLICY "Participants can update their registration"
  ON public.tournament_participants
  FOR UPDATE
  USING (user_id = public.current_profile_id() OR public.is_team_owner(team_id));

CREATE POLICY "Users can leave tournaments"
  ON public.tournament_participants
  FOR DELETE
  USING (user_id = public.current_profile_id() OR public.is_team_owner(team_id));


-- =============================================================================
-- 5. POLICIES -- public.fixtures
-- Only the tournament organizer may schedule or edit fixtures.
-- =============================================================================

DROP POLICY IF EXISTS "Anyone can view fixtures"       ON public.fixtures;
DROP POLICY IF EXISTS "Organizers can create fixtures" ON public.fixtures;
DROP POLICY IF EXISTS "Organizers can update fixtures" ON public.fixtures;
DROP POLICY IF EXISTS "Organizers can delete fixtures" ON public.fixtures;

CREATE POLICY "Anyone can view fixtures"
  ON public.fixtures
  FOR SELECT
  USING (true);

CREATE POLICY "Organizers can create fixtures"
  ON public.fixtures
  FOR INSERT
  WITH CHECK (public.is_tournament_organizer(tournament_id));

CREATE POLICY "Organizers can update fixtures"
  ON public.fixtures
  FOR UPDATE
  USING (public.is_tournament_organizer(tournament_id))
  WITH CHECK (public.is_tournament_organizer(tournament_id));

CREATE POLICY "Organizers can delete fixtures"
  ON public.fixtures
  FOR DELETE
  USING (public.is_tournament_organizer(tournament_id));


-- =============================================================================
-- 6. POLICIES -- public.fixture_results
--
-- The submitter is either the tournament organizer or a participant of the
-- fixture. fixture_results is NEVER referenced inside its own policies -- doing
-- so would recurse infinitely through RLS. Only public.fixtures and
-- public.tournament_participants are read here.
--
-- Scores must be non-negative. There is no DELETE policy.
-- =============================================================================

DROP POLICY IF EXISTS "Anyone can view fixture results" ON public.fixture_results;
DROP POLICY IF EXISTS "Participants and organizers can submit results" ON public.fixture_results;

CREATE POLICY "Anyone can view fixture results"
  ON public.fixture_results
  FOR SELECT
  USING (true);

CREATE POLICY "Participants and organizers can submit results"
  ON public.fixture_results
  FOR INSERT
  WITH CHECK (
    submitted_by = public.current_profile_id()
    AND (
      public.is_tournament_organizer(
        (SELECT f.tournament_id FROM public.fixtures f WHERE f.id = fixture_id)
      )
      OR EXISTS (
        SELECT 1
        FROM public.fixtures f
        JOIN public.tournament_participants tp
          ON tp.id IN (f.home_participant_id, f.away_participant_id)
        WHERE f.id = fixture_id
          AND tp.user_id = public.current_profile_id()
      )
    )
    AND (home_score IS NULL OR home_score >= 0)
    AND (away_score IS NULL OR away_score >= 0)
  );

DROP POLICY IF EXISTS "Participants and organizers can update results" ON public.fixture_results;

CREATE POLICY "Participants and organizers can update results"
  ON public.fixture_results
  FOR UPDATE
  USING (
    submitted_by = public.current_profile_id()
    AND (
      public.is_tournament_organizer(
        (SELECT f.tournament_id FROM public.fixtures f WHERE f.id = fixture_id)
      )
      OR EXISTS (
        SELECT 1
        FROM public.fixtures f
        JOIN public.tournament_participants tp
          ON tp.id IN (f.home_participant_id, f.away_participant_id)
        WHERE f.id = fixture_id
          AND tp.user_id = public.current_profile_id()
      )
    )
  )
  WITH CHECK (
    submitted_by = public.current_profile_id()
    AND (
      public.is_tournament_organizer(
        (SELECT f.tournament_id FROM public.fixtures f WHERE f.id = fixture_id)
      )
      OR EXISTS (
        SELECT 1
        FROM public.fixtures f
        JOIN public.tournament_participants tp
          ON tp.id IN (f.home_participant_id, f.away_participant_id)
        WHERE f.id = fixture_id
          AND tp.user_id = public.current_profile_id()
      )
    )
    AND (home_score IS NULL OR home_score >= 0)
    AND (away_score IS NULL OR away_score >= 0)
  );


-- =============================================================================
-- 7. POLICIES -- public.teams
-- =============================================================================

DROP POLICY IF EXISTS "Anyone can view teams"      ON public.teams;
DROP POLICY IF EXISTS "Users can create teams"     ON public.teams;
DROP POLICY IF EXISTS "Team owners can update teams" ON public.teams;
DROP POLICY IF EXISTS "Team owners can delete teams" ON public.teams;

CREATE POLICY "Anyone can view teams"
  ON public.teams
  FOR SELECT
  USING (true);

CREATE POLICY "Users can create teams"
  ON public.teams
  FOR INSERT
  WITH CHECK (owner_id = public.current_profile_id());

CREATE POLICY "Team owners can update teams"
  ON public.teams
  FOR UPDATE
  USING (public.is_team_owner(id))
  WITH CHECK (public.is_team_owner(id));

CREATE POLICY "Team owners can delete teams"
  ON public.teams
  FOR DELETE
  USING (public.is_team_owner(id));


-- =============================================================================
-- 8. POLICIES -- public.team_members
-- No UPDATE policy needed.
-- =============================================================================

DROP POLICY IF EXISTS "Anyone can view team members" ON public.team_members;
DROP POLICY IF EXISTS "Users can join teams"          ON public.team_members;
DROP POLICY IF EXISTS "Members can leave teams"       ON public.team_members;

CREATE POLICY "Anyone can view team members"
  ON public.team_members
  FOR SELECT
  USING (true);

CREATE POLICY "Users can join teams"
  ON public.team_members
  FOR INSERT
  WITH CHECK (user_id = public.current_profile_id() OR public.is_team_owner(team_id));

CREATE POLICY "Members can leave teams"
  ON public.team_members
  FOR DELETE
  USING (user_id = public.current_profile_id() OR public.is_team_owner(team_id));


-- =============================================================================
-- 9. GRANTS
--
-- Required: RLS restricts rows, but without these privileges PostgREST cannot
-- read anything at all. View grants live here (not in 03) because
-- CREATE OR REPLACE VIEW does not preserve grants on an existing view.
-- =============================================================================

GRANT USAGE ON SCHEMA public TO anon, authenticated;

-- Read access to every base table (RLS still filters rows).
GRANT SELECT ON ALL TABLES IN SCHEMA public TO anon, authenticated;

-- Write access for signed-in users, still subject to the policies above.
GRANT INSERT, UPDATE, DELETE ON
    public.tournaments,
    public.tournament_participants,
    public.fixtures,
    public.fixture_results,
    public.teams,
    public.team_members
  TO authenticated;

-- Views defined in 03_views.sql.
GRANT SELECT ON
    public.tournament_standings,
    public.player_tournament_stats,
    public.player_rankings
  TO anon, authenticated;

-- Function execution.
GRANT EXECUTE ON FUNCTION public.generate_fixtures(uuid)       TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_next_round(uuid)    TO authenticated;
GRANT EXECUTE ON FUNCTION public.current_profile_id()          TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_tournament_organizer(uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_team_owner(uuid)           TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_team_member(uuid)          TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_join_tournament(uuid)     TO authenticated;


-- =============================================================================
-- End of 04_rls_grants.sql
-- =============================================================================
